package warden

// A memberShard is an encrypted shard that may be unlocked with the
// use of a matching credential + some server provided arguments.
type memberShard struct {
	Id       []byte
	Proto    authProtocol
	Raw      SignedEncryptedShard
	AuthArgs []byte // optional (These are generated by the )
}
